### ISSUE TITLE
[sql] null values are inserted as string "null"

### ISSUE THREAD

**Issue by damingo** [tauri-apps/plugins-workspace#11]
A query query like this
```
await db.execute('INSERT INTO settings(name, value) VALUES($1, $2)', ['test', null])
```
inserts the string "null" into the `value` column.

**Comment by joehillen** [comment]
Is there a workaround for this?

**Comment by damingo** [comment]
> Is there a workaround for this?

A composed query similar to this: 

```js
    // Executes a "Insert if not exists"
    // table: Table name
    // columnNames: (Array) The table must have a 'uid' that must not be passed in.
    // fields:
    async insert({table, columnNames, fields}) {
        try {
            // `uid` must be the first column as it is referenced in the insert statement (see below).
            columnNames = ['uid', ...columnNames]
            let columns = []
            let columnReferences = []
            let values = []
            let counter = 1
            // NOTE: A composed query is required as NULL values in the values array are otherwise inserted
            // as string values 'NULL'. (2022-03-02)
            // See: https://github.com/tauri-apps/plugins-workspace/issues/11 columns with NULL values must be excluded.
            columnNames.filter(attr => fields.hasOwnProperty(camelize(attr)) && fields[camelize(attr)] !== null)
                .forEach(attr => {
                    columns.push(attr)
                    columnReferences.push(`$${counter}`)
                    values.push(fields[camelize(attr)])
                    counter += 1
                })
            let query = `INSERT INTO ${table} (${columns.join(', ')})
                         SELECT ${columnReferences.join(', ')}
                         WHERE NOT EXISTS(SELECT 1 FROM ${table} WHERE uid = $1)`
            return await this.db.execute(query, values)
        } catch (error) {
            this.handleError(error)
        }
    }
```

**Comment by olingern** [comment]
Possibly related
https://github.com/tauri-apps/plugins-workspace/issues/10

**Comment by joakim** [comment]
I have a workaround that uses (safe) string interpolation to explicitly set the value to `NULL` if it's either `null` or `undefined`:

```js
await db.execute(`INSERT INTO settings (name, value) VALUES ($1, ${ (value ?? null) === null ? 'NULL' : '$2' })`, [name, value])
```

If that's too long or boilerplaty, you could break it out as a function:

```js
const nullable = (value, index) => (value ?? null) === null ? 'NULL' : '$' + index
```

```js
await db.execute(`INSERT INTO settings (name, value) VALUES ($1, ${ nullable(value, 2) })`, [name, value])
```

I think this SQL plugin needs some attention. There are too many data type bugs to be usable beyond the most basic use cases. I would give it a try if I was familiar with Rust, unfortunately I can only contribute on the JS end.

**Comment by HarshilSharaf** [comment]
@JonasKruckenberg, @lucasfernog, @FabianLars ,this issue still persists when I try to execute a stored procedure, it takes null values as 'null'  and stores as 'null' string in my database. Following is the query that i use :

```
this.databaseService.dbConnection.select(`call add_customer(
      ?,?,?,?,?,?,?,?,?);
      `, [customerDetails.firstName,
    customerDetails.lastName,
    dayjs(customerDetails.dateOfBirth).format('YYYY-MM-DD'),
    customerDetails.gender,
    customerDetails.address,
    customerDetails.city,
    customerDetails.email,
    customerDetails.phoneNumber,
    customerDetails.imagePath])
```

In above snippet imagePath can be null ...but while executing the above sp it stores null  as a string
Also , it stores empty string as '' in the database instead of storing it as null value.

Can we expect anytime soon for the fix?

**Comment by FabianLars** [comment]
~~Could you try the `sql/null` branch of this plugin please? <https://github.com/tauri-apps/plugins-workspace/pull/278>~~

Edit: Nevermind, i merged it into `dev`, so a simple `cargo update` should pull the fix in for you.

**Comment by HarshilSharaf** [comment]
> 
Hi @FabianLars ,
It looks like your fix didn't work out. I am still facing the same issue. Am I passing the values in the correct format?

I am attaching the screenshot of console.log : 
![image](https://user-images.githubusercontent.com/62461329/224769195-95d427e7-8271-4e74-9d2d-6ae2543bdf54.png)

**Comment by FabianLars** [comment]
No idea to be honest. i'm not a sql expert so your query looks honestly a bit weird to me. I used the `$1`, `$2` syntax from the other comments to test it.

Note, that nothing changed how the plugin _reads_ the database, only how it saves `null` values

Edit: imagePath in your screenshot now is correctly set to `null` so i guess the fix worked? I didn't touch empty strings at all since i don't feel like this is something the plugin should handle automatically.

**Comment by HarshilSharaf** [comment]
> No idea to be honest. i'm not a sql expert so your query looks honestly a bit weird to me. I used the `$1`, `$2` syntax from the other comments to test it.
> 
> Note, that nothing changed how the plugin _reads_ the database, only how it saves `null` values

In MySql you need to pass values like what i did...So $1 is not supported by MySql😁

**Comment by HarshilSharaf** [comment]
> 



> Edit: imagePath in your screenshot now is correctly set to `null` so i guess the fix worked? I didn't touch empty strings at all since i don't feel like this is something the plugin should handle automatically

The screenshot i provided is actually before passing it to the query

**Comment by HarshilSharaf** [comment]
@FabianLars  I noticed something strange...When i perform the same query using `execute()` method it works correctly (null values are stored as null onlly and not as a string).
But not with `select()` method...This you might want to notice


JUST FYI : My Stored Procedure returns some data so..i really need to use the `select()` method instead of `execute()`

**Comment by FabianLars** [comment]
oh shit, you're right. i'm going to push a fix real quick, sorry!

**Comment by HarshilSharaf** [comment]
> oh shit, you're right. i'm going to push a fix real quick, sorry!

Great! 
Looks like providing a heads up worked🤜🤛
