### ISSUE TITLE
[bug] plugin-http reporting TypeError: ReadableStreamDefaultController is not in a state where it can be closed

### ISSUE THREAD

**Issue by perezd** [tauri-apps/plugins-workspace#2533]
I am using the `fetch` JS API from plugin-http. Here's the exact function I've written that produces the failure:

```
import { LATITUDE_API_KEY, LATITUDE_PROJECT_ID } from '$lib/flags';
import { render } from 'promptl-ai';

async function prompt(path: string, parameters: Record<string, unknown>) {
  const response = await fetch(
    `https://gateway.latitude.so/api/v3/projects/${LATITUDE_PROJECT_ID}/versions/live/documents/${path}`,
    {
      headers: {
        Authorization: `Bearer ${LATITUDE_API_KEY}`
      }
    }
  );
  if (response.status !== 200) throw new Error(`Failed to fetch prompt ${path}`);
  const { content: prompt } = await response.json();
  return render({ prompt, parameters });
}
```
my permissions config is:

```
    {
      "identifier": "http:default",
      "allow": [{ "url": "https://gateway.latitude.so" }]
    },
```

The request goes through and I get the response even, this failure happens after everything worked, so it seems to be a logic bug of some kind.

Happy to provide other diagnostics if helpful. The failure is happening within the `fetch` function itself provided by the plugin...near the line that says `controller.close()` here: https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/http/guest-js/index.ts#L206

**Comment by amrbashir** [comment]
we just merged a PR related to this, could you give it a try?

**Comment by perezd** [comment]
Sure, can you give me some pointers on how to try it out?

**Comment by developit** [comment]
FWIW I was seeing this yesterday and the merged PR fixed it.

~I still can't get responses to yield in JS though (both via response.body or response.text). I'm on http 2.4.1. The Promises just never respond.~ nevermind, my fault!

**Comment by amrbashir** [comment]
> Sure, can you give me some pointers on how to try it out?

It is published, try updating to latest version which should be 2.4.1

**Comment by perezd** [comment]
Confirmed, this appears fixed!
