### ISSUE TITLE
d.ts is not included

### ISSUE THREAD

**Issue by HuakunShen** [tauri-apps/plugins-workspace#76]
After running `npm add https://github.com/tauri-apps/tauri-plugin-store` I couldn't import the module

`import { Store } from "tauri-plugin-store-api";` doesn't work.

I checked the node_modules, it seems like it's because no `d.ts` is present in the dist folder.

**Comment by HuakunShen** [comment]
The fix is adding `guest-js` folder to `package.json` -> "files"

I am using a fork. Please fix it. The problem exists for all plugin npm packages.

**Comment by FabianLars** [comment]
Should be fixed now, thank you.

**Comment by mBaratta96** [comment]
Hello. Sorry, but the error is still there. Adding the package with `yarn add tauri-plugin-store-api@https://github.com/tauri-apps/tauri-plugin-store` still makes all the `d.ts` file absent.

[HuakunShen's solution](https://github.com/tauri-apps/tauri-plugin-store/commit/fe2671db67e248716a8e03e5ba88747bc58493ad) seems to work.

**Comment by FabianLars** [comment]
Can't reproduce it with yarn anymore either. Maybe it's a cache issue? (= yarn still installing the old commit?)

**Comment by mBaratta96** [comment]
I tried to run a `yarn cache clean` and then `yarn add tauri-plugin-store-api@https://github.com/tauri-apps/tauri-plugin-store`. Nothing changed.

I believe the new configuration in `package.json` is still not correct:
```json
  "files": [
    "guest-js/dist",
    "!guest-js/dist/**/*.map",
    "README.md",
    "LICENSE"
  ],
```
Huakun's solution, however, makes everything work:
```json
"files": [
    "guest-js",
    "dist",
    "!dist/**/*.map",
    "README.md",
    "LICENSE"
  ],
```

**Comment by FabianLars** [comment]
Can you show a screenshot of the error and maybe a snippet of the problematic code?

**Comment by mBaratta96** [comment]
This is what happens when I run `yarn add tauri-plugin-store-api@https://github.com/tauri-apps/tauri-plugin-store`:

- My `package.json`:

![](https://user-images.githubusercontent.com/37810930/211918347-e0956892-164b-40f1-8579-96a6790e0fd1.png)
- The plugin in `node_modules` (absence of any Typescript file):

![](https://user-images.githubusercontent.com/37810930/211918503-26d04913-ad98-4275-85db-5a0391b7890a.png)
- What I get in the code when I import the `Store`:

![](https://user-images.githubusercontent.com/37810930/211918598-f8a7a877-b623-4daa-8624-504b84d41262.png)

As a counterexample, this is what I get if I add [Huakun's fork](https://github.com/HuakunShen/tauri-plugin-store) with `yarn add tauri-plugin-store-api@https://github.com/HuakunShen/tauri-plugin-store`:

- My `package.json`:

![](https://user-images.githubusercontent.com/37810930/211918953-4426761a-543b-4d5c-9804-08f9e0a10630.png)

- The plugin in `node_modules` (Typescript files are present):

![](https://user-images.githubusercontent.com/37810930/211919041-f43320ee-aa93-435d-9af2-26022689a1a2.png)

- The same code:

![](https://user-images.githubusercontent.com/37810930/211919121-758de3a2-0eed-4015-8f62-3986bd566cb5.png)

**Comment by FabianLars** [comment]
Okay thank you. Last thing, what's your yarn version?

**Comment by mBaratta96** [comment]
Yarn version is `3.3.1`. Thanks

**Comment by FabianLars** [comment]
Interesting. I can reproduce it with Yarn Berry (3) too. It works fine with npm, pnpm and yarn classic (1) tho 😞

**Comment by mBaratta96** [comment]
I'll work with the fork for a while. Is there any chance this will be fixed in the near future? Just to consider the option of downgrading Yarn. Thanks a lot.

**Comment by FabianLars** [comment]
Yeah it will be fixed, i just don't like including the whole guest-js file like in the fork because that also includes all the source code files, so i'll need to find another way.

**Comment by FabianLars** [comment]
Alrightyyy, please tell me that it works for you now 😂

**Comment by mBaratta96** [comment]
Works great! Thank you so much.
